/**
 * Generates the flag catalog and every lookup table derived from flags/ and data/:
 *
 *   flags/index.ts                    flagList (every key, sorted) + flagLoaders (lazy, one chunk per flag)
 *   src/generated/national.ts         national flags, imported eagerly by the main entry
 *   src/generated/countries/<CC>.ts   registers every key of one country (open-flags/countries/<CC>)
 *   src/generated/all.ts              imports every country module (open-flags/all)
 *   src/iso-mapping.json              ISO code -> local flag artwork, with regional / national polyfills
 *   src/iso-coa-mapping.json          the same for coats of arms
 *   packages/open-flags-api/src/generated/iso-mapping.json, iso-coa-mapping.json
 *                                     the same, resolved against what the Open Flags API serves
 *   src/named-mapping.json            English names and 0.0.5 legacy names -> location
 *   src/i18n/<locale>.json            ISO <-> name pairs in the Open Flags API's i18n format
 *   src/i18n/aliases.json             ISO code -> English aliases
 *
 * Flag key = path relative to flags/ without ".svg", forward slashes:
 *
 *   flags/<CC>.svg          national flag          flags/<CC>-COA.svg          national coat of arms
 *   flags/<CC>/<SUB>.svg    subdivision flag       flags/<CC>/<SUB>-COA.svg    subdivision coat of arms
 *   flags/<CC>-<slug>.svg   extra flag associated with a country (not an ISO code)
 *
 * Inputs: flags/ (the tree is read once, SVGs are never parsed), data/iso-codes.json,
 * data/api-availability.json and data/legacy-aliases.json. The output is deterministic (sorted keys,
 * stable formatting) and files are only rewritten when their content changes.
 *
 * Usage:
 *   npm run gen:flags
 */
import fs from 'fs';
import path from 'path';

type Locale = 'en' | 'es' | 'zh-CN' | 'zh-TW';
type Status = 'current' | 'withdrawn' | 'user-assigned';
type PolyfillLevel = 'regional' | 'national';
type Names = Partial<Record<Locale, string>>;

interface CountryRecord {
  status: Status;
  names: Names;
  aliases?: string[];
}

interface SubdivisionRecord {
  country: string;
  status: Status;
  type?: string;
  parent?: string;
  names: Names;
  aliases?: string[];
}

interface IsoData {
  countries: Record<string, CountryRecord>;
  subdivisions: Record<string, SubdivisionRecord>;
}

interface ApiAvailability {
  flags: string[];
  coats: string[];
}

/** Same shape as IsoLocation in src/core/types.ts. */
interface IsoLocation {
  country: string;
  subdivision: string | null;
  polyfill?: PolyfillLevel;
  status?: Exclude<Status, 'current'>;
}

type Kind = 'national' | 'national-coat' | 'subdivision' | 'subdivision-coat' | 'variant' | 'extra' | 'unmatched';

interface FlagFile {
  key: string; // e.g. 'GB/CON'
  file: string; // path relative to flags/, e.g. 'GB/CON_.svg'
  kind: Kind;
  country: string | null; // country module that registers the key
  iso?: string; // ISO code of a national / subdivision flag or coat of arms
}

const ROOT = path.resolve(__dirname, '..');
const FLAGS_DIR = path.join(ROOT, 'flags');
const GENERATED_DIR = path.join(ROOT, 'src/generated');
const COUNTRIES_DIR = path.join(GENERATED_DIR, 'countries');
const API_GENERATED_DIR = path.join(ROOT, 'packages/open-flags-api/src/generated');
const HEADER = '// Generated by scripts/generateFlagMap.ts — do not edit.';
const LOCALES: Record<Locale, { name: string; native: string }> = {
  en: { name: 'English', native: 'English' },
  es: { name: 'Spanish', native: 'Español' },
  'zh-CN': { name: 'Chinese (Simplified)', native: '简体中文' },
  'zh-TW': { name: 'Chinese (Traditional)', native: '繁體中文' },
};

/**
 * Windows reserves device names as file names (with any extension) and git for Windows refuses to
 * check them out, so a subdivision whose ISO suffix is one of them is stored as "<SUB>_.svg"
 * (e.g. Cornwall, GB-CON -> flags/GB/CON_.svg). Its flag key is still "GB/CON".
 */
const WINDOWS_RESERVED = /^(CON|PRN|AUX|NUL|COM[0-9¹²³]|LPT[0-9¹²³])$/i;
const KEBAB = /^[a-z0-9]+(-[a-z0-9]+)*$/;

function readJson<T>(file: string): T {
  return JSON.parse(fs.readFileSync(path.join(ROOT, file), 'utf8')) as T;
}

/** Code-unit order, so the output never depends on the machine's locale. */
function compare(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

function sortObject<T>(obj: Record<string, T>): Record<string, T> {
  return Object.fromEntries(Object.entries(obj).sort(([a], [b]) => compare(a, b)));
}

/** Every file below `dir` as a forward-slash path relative to it (one readdir per directory). */
function walkDir(dir: string, prefix = ''): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
    const rel = `${prefix}${entry.name}`;
    return entry.isDirectory() ? walkDir(path.join(dir, entry.name), `${rel}/`) : [rel];
  });
}

/** 'GB/CON_.svg' -> 'GB/CON': the path without '.svg', minus the '_' that protects a reserved name. */
function keyFor(file: string): string {
  const key = file.slice(0, -'.svg'.length);
  const base = key.slice(key.lastIndexOf('/') + 1);
  return base.endsWith('_') && WINDOWS_RESERVED.test(base.slice(0, -1)) ? key.slice(0, -1) : key;
}

/** The file a key is stored in: 'GB/CON' -> 'GB/CON_.svg'. */
function fileFor(key: string): string {
  return WINDOWS_RESERVED.test(key.slice(key.lastIndexOf('/') + 1)) ? `${key}_.svg` : `${key}.svg`;
}

/** 'US-CA' -> { country: 'US', subdivision: 'CA' }, 'US' -> { country: 'US', subdivision: null }. */
function isoLocation(code: string): IsoLocation {
  const dash = code.indexOf('-');
  return dash === -1
    ? { country: code, subdivision: null }
    : { country: code.slice(0, dash), subdivision: code.slice(dash + 1) };
}

/** Location that reproduces an exact flag key: 'MX/MIC-COA' -> { country: 'MX', subdivision: 'MIC-COA' }. */
function keyLocation(key: string): IsoLocation {
  const slash = key.indexOf('/');
  return slash === -1
    ? { country: key, subdivision: null }
    : { country: key.slice(0, slash), subdivision: key.slice(slash + 1) };
}

/** Single-quoted TS string literal. */
function quote(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\r/g, '\\r').replace(/\n/g, '\\n')}'`;
}

/** Import identifiers (the original sanitizing rule), numbered when two keys sanitize alike. */
function identifiers(keys: string[]): Map<string, string> {
  const ids = new Map<string, string>();
  const used = new Set<string>();
  for (const key of keys) {
    const base = `${/^\d/.test(key) ? '_' : ''}${key.replace(/\W/g, '_')}_svg`;
    let id = base;
    for (let n = 2; used.has(id); n++) id = `${base}_${n}`;
    used.add(id);
    ids.set(key, id);
  }
  return ids;
}

/**
 * ISO code -> location of the artwork served for it, for every code that resolves to something:
 * its own artwork, else the first ancestor subdivision (walking `parent` links) with artwork of its
 * own (polyfill "regional"), else the country's national artwork (polyfill "national"). Codes that
 * resolve to nothing are omitted. `has` holds the ISO codes that have artwork of their own.
 */
function buildMapping(iso: IsoData, codes: string[], has: Set<string>): Record<string, IsoLocation> {
  const mapping: Record<string, IsoLocation> = {};
  for (const code of codes) {
    const sub: SubdivisionRecord | undefined = iso.subdivisions[code];
    const status = sub ? sub.status : iso.countries[code].status;
    let target = has.has(code) ? code : undefined;
    let polyfill: PolyfillLevel | undefined;
    if (!target && sub) {
      const seen = new Set([code]);
      for (let parent = sub.parent; parent && !seen.has(parent); parent = iso.subdivisions[parent]?.parent) {
        seen.add(parent);
        if (has.has(parent)) {
          target = parent;
          polyfill = 'regional';
          break;
        }
      }
      if (!target && has.has(sub.country)) {
        target = sub.country;
        polyfill = 'national';
      }
    }
    if (target) {
      mapping[code] = {
        ...isoLocation(target),
        ...(polyfill ? { polyfill } : {}),
        ...(status !== 'current' ? { status } : {}),
      };
    }
  }
  return mapping;
}

function main(): void {
  const started = Date.now();
  const iso = readJson<IsoData>('data/iso-codes.json');
  const api = readJson<ApiAvailability>('data/api-availability.json');
  const legacy = readJson<Record<string, string>>('data/legacy-aliases.json');
  const countryCodes = Object.keys(iso.countries).sort(compare);
  const subdivisionCodes = Object.keys(iso.subdivisions).sort(compare);
  const codes = [...countryCodes, ...subdivisionCodes].sort(compare);
  const knownCountries = new Set(countryCodes);
  const knownSubdivisions = new Set(subdivisionCodes);
  const statusOf = (code: string): Status | undefined => (iso.subdivisions[code] ?? iso.countries[code])?.status;
  let warnings = 0;
  const warn = (message: string) => {
    warnings++;
    console.warn(`Warning: ${message}`);
  };
  const outputs = new Map<string, string>();
  const json = (data: unknown): string => `${JSON.stringify(data, null, 2)}\n`;

  // --- flags/: one pass over the tree ----------------------------------------------------------
  const classify = (key: string): Pick<FlagFile, 'kind' | 'country' | 'iso'> => {
    const slash = key.indexOf('/');
    if (slash === -1) {
      if (/^[A-Z]{2}$/.test(key)) return { kind: 'national', country: key, iso: key };
      const m = /^([A-Z]{2})-(.+)$/.exec(key);
      if (m) return m[2] === 'COA' ? { kind: 'national-coat', country: m[1], iso: m[1] } : { kind: 'extra', country: m[1] };
    } else {
      const cc = key.slice(0, slash);
      const base = key.slice(slash + 1);
      if (/^[A-Z]{2}$/.test(cc)) {
        // 'COA-COA' is the coat of arms of MX-COA (Coahuila), 'COA' its flag.
        const coatOf = base.endsWith('-COA') ? `${cc}-${base.slice(0, -'-COA'.length)}` : undefined;
        if (coatOf && knownSubdivisions.has(coatOf)) return { kind: 'subdivision-coat', country: cc, iso: coatOf };
        if (knownSubdivisions.has(`${cc}-${base}`)) return { kind: 'subdivision', country: cc, iso: `${cc}-${base}` };
        // '<SUB>-<Variant>' (e.g. US/GA-Classic, KR/26-pre-2023) is an alternate or superseded design of that
        // subdivision's flag. ISO suffixes never contain '-', so the first '-' separates the variant.
        const dash = base.indexOf('-');
        if (dash > 0 && knownSubdivisions.has(`${cc}-${base.slice(0, dash)}`)) {
          return { kind: 'variant', country: cc, iso: `${cc}-${base.slice(0, dash)}` };
        }
      }
    }
    return { kind: 'unmatched', country: /^([A-Z]{2})(?=$|[/-])/.exec(key)?.[1] ?? null };
  };

  const byKey = new Map<string, FlagFile>();
  for (const file of walkDir(FLAGS_DIR).sort(compare)) {
    if (!file.endsWith('.svg')) {
      if (file !== 'index.ts') warn(`flags/${file} is not an .svg file, ignored`);
      continue;
    }
    const key = keyFor(file);
    const flag: FlagFile = { key, file, ...classify(key) };
    if (flag.kind === 'unmatched') {
      warn(`flags/${file} fits no file rule (key '${key}'), kept in flagList`);
    } else if (!flag.key.includes('/') && flag.country && !knownCountries.has(flag.country)) {
      warn(`flags/${file}: ${flag.country} is not a country in data/iso-codes.json`);
    }
    if (flag.kind === 'extra' && !KEBAB.test(key.slice(3))) warn(`flags/${file}: extra flag slug is not kebab-case`);
    const existing = byKey.get(key);
    if (existing) {
      const keep = file === fileFor(key) ? flag : existing;
      warn(`flags/${existing.file} and flags/${file} have the same key '${key}', using flags/${keep.file}`);
      byKey.set(key, keep);
    } else {
      byKey.set(key, flag);
    }
  }
  const flags = [...byKey.values()].sort((a, b) => compare(a.key, b.key));

  // --- flags/index.ts: catalog + lazy loaders (one chunk per flag) --------------------------------
  outputs.set(
    path.join(FLAGS_DIR, 'index.ts'),
    [
      HEADER,
      'export const flagList: string[] = [',
      ...flags.map(f => `  ${quote(f.key)},`),
      '];',
      '',
      'export const flagLoaders: Record<string, () => Promise<{ default: string }>> = {',
      ...flags.map(f => `  ${quote(f.key)}: () => import(${quote(`./${f.file}`)}),`),
      '};',
      '',
    ].join('\n')
  );

  // --- src/generated: eager national flags, per-country registration, all ------------------------
  const national = flags.filter(f => /^[A-Z]{2}$/.test(f.key));
  const nationalIds = identifiers(national.map(f => f.key));
  outputs.set(
    path.join(GENERATED_DIR, 'national.ts'),
    [
      HEADER,
      ...national.map(f => `import ${nationalIds.get(f.key)} from ${quote(`../../flags/${f.file}`)};`),
      '',
      'export const nationalFlags: Record<string, string> = {',
      ...national.map(f => `  ${quote(f.key)}: ${nationalIds.get(f.key)},`),
      '};',
      '',
    ].join('\n')
  );

  const byCountry = new Map<string, FlagFile[]>();
  for (const f of flags) {
    if (!f.country) continue;
    const list = byCountry.get(f.country);
    if (list) list.push(f);
    else byCountry.set(f.country, [f]);
  }
  const countryModules = [...byCountry.keys()].sort(compare);
  for (const cc of countryModules) {
    const list = byCountry.get(cc) ?? [];
    const ids = identifiers(list.map(f => f.key));
    outputs.set(
      path.join(COUNTRIES_DIR, `${cc}.ts`),
      [
        HEADER,
        "import { registerFlags } from '../../registry';",
        ...list.map(f => `import ${ids.get(f.key)} from ${quote(`../../../flags/${f.file}`)};`),
        '',
        'registerFlags({',
        ...list.map(f => `  ${quote(f.key)}: ${ids.get(f.key)},`),
        '});',
        '',
      ].join('\n')
    );
  }
  outputs.set(
    path.join(GENERATED_DIR, 'all.ts'),
    [HEADER, ...countryModules.map(cc => `import ${quote(`./countries/${cc}`)};`), ''].join('\n')
  );

  // --- ISO mappings: local artwork and what the API serves ----------------------------------------
  const ownArtwork = (kinds: Kind[]) =>
    new Set(flags.filter(f => f.iso && kinds.includes(f.kind)).map(f => f.iso as string));
  const isoMapping = buildMapping(iso, codes, ownArtwork(['national', 'subdivision']));
  const coaMapping = buildMapping(iso, codes, ownArtwork(['national-coat', 'subdivision-coat']));
  const apiMapping = buildMapping(iso, codes, new Set(api.flags));
  const apiCoaMapping = buildMapping(iso, codes, new Set(api.coats));
  outputs.set(path.join(ROOT, 'src/iso-mapping.json'), json(isoMapping));
  outputs.set(path.join(ROOT, 'src/iso-coa-mapping.json'), json(coaMapping));
  outputs.set(path.join(API_GENERATED_DIR, 'iso-mapping.json'), json(apiMapping));
  outputs.set(path.join(API_GENERATED_DIR, 'iso-coa-mapping.json'), json(apiCoaMapping));

  // --- named-mapping.json: English names, then the 0.0.5 legacy names ---------------------------
  // Collisions: own artwork first, then current status, then the first code. A legacy name fills a key
  // no modern name uses, and also replaces a modern name that only resolves to a polyfill: the 0.0.5
  // artwork for that name (e.g. MEXICO-CAMPECHE -> MX/CAM-COA) is more specific than a national flag.
  const named = new Map<string, IsoLocation>();
  const rank = (loc: IsoLocation): number => (loc.polyfill ? 2 : 0) + (loc.status ? 1 : 0);
  for (const code of codes) {
    const loc = isoMapping[code];
    if (!loc) continue;
    const sub: SubdivisionRecord | undefined = iso.subdivisions[code];
    const countryName = iso.countries[sub ? sub.country : code]?.names.en;
    const subName = sub?.names.en;
    if (!countryName || (sub && !subName)) continue;
    const key = (sub ? `${countryName}-${subName}` : countryName).toUpperCase();
    const existing = named.get(key);
    if (!existing || rank(loc) < rank(existing)) named.set(key, loc);
  }
  const modernNames = new Set(named.keys());
  let shadowed = 0;
  let legacyOverPolyfill = 0;
  for (const [oldKey, newKey] of Object.entries(legacy).sort(([a], [b]) => compare(a, b))) {
    const slash = oldKey.indexOf('/');
    const key = (slash === -1 ? oldKey : `${oldKey.slice(0, slash)}-${oldKey.slice(slash + 1)}`).toUpperCase();
    const target = byKey.get(newKey);
    if (!target) {
      warn(`data/legacy-aliases.json: '${oldKey}' -> '${newKey}' is not a flag key, skipped`);
      continue;
    }
    const status = target.iso ? statusOf(target.iso) : undefined;
    const loc: IsoLocation = { ...keyLocation(newKey), ...(status && status !== 'current' ? { status } : {}) };
    const existing = named.get(key);
    if (existing && JSON.stringify(existing) !== JSON.stringify(loc)) {
      if (modernNames.has(key)) shadowed++;
      else warn(`data/legacy-aliases.json: '${oldKey}' and an earlier alias both map ${key}, keeping the first`);
    }
    if (!existing) named.set(key, loc);
    else if (existing.polyfill && modernNames.has(key)) {
      named.set(key, loc);
      legacyOverPolyfill++;
      shadowed--;
    }
  }
  outputs.set(path.join(ROOT, 'src/named-mapping.json'), json(sortObject(Object.fromEntries(named))));

  // --- i18n: ISO <-> name pairs per locale (Open Flags API format) and English aliases ------------
  for (const [locale, meta] of Object.entries(LOCALES) as [Locale, { name: string; native: string }][]) {
    const countries: Record<string, string> = {};
    const subdivisions: Record<string, string> = {};
    for (const code of countryCodes) {
      const name = iso.countries[code].names[locale];
      if (name) countries[code] = name;
    }
    for (const code of subdivisionCodes) {
      const name = iso.subdivisions[code].names[locale];
      if (name) subdivisions[code] = name;
    }
    outputs.set(
      path.join(ROOT, 'src/i18n', `${locale}.json`),
      json({
        _meta: {
          language: locale,
          language_name: meta.name,
          language_native: meta.native,
          description: `${meta.name} names of ISO 3166 countries (_countries) and subdivisions (every other key), in the Open Flags API i18n format. Only names that exist in this language are listed. Generated by scripts/generateFlagMap.ts from data/iso-codes.json - do not edit by hand.`,
        },
        _countries: countries,
        ...subdivisions,
      })
    );
  }
  const aliases: Record<string, string[]> = {};
  for (const code of codes) {
    const list = (iso.subdivisions[code] ?? iso.countries[code]).aliases;
    if (list?.length) aliases[code] = list;
  }
  outputs.set(path.join(ROOT, 'src/i18n/aliases.json'), json(aliases));

  // --- write ---------------------------------------------------------------------------------
  let written = 0;
  for (const [file, content] of outputs) {
    if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === content) continue;
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    written++;
  }
  let removed = 0;
  for (const file of fs.existsSync(COUNTRIES_DIR) ? fs.readdirSync(COUNTRIES_DIR) : []) {
    if (file.endsWith('.ts') && !byCountry.has(file.slice(0, -'.ts'.length))) {
      fs.unlinkSync(path.join(COUNTRIES_DIR, file));
      removed++;
    }
  }

  const count = (kind: Kind) => flags.filter(f => f.kind === kind).length;
  const split = (mapping: Record<string, IsoLocation>) => {
    const locs = Object.values(mapping);
    const polyfilled = (level: PolyfillLevel) => locs.filter(l => l.polyfill === level).length;
    return `${locs.length} codes (${locs.filter(l => !l.polyfill).length} own, ${polyfilled('regional')} regional, ${polyfilled('national')} national polyfills)`;
  };
  console.log(
    `flags/index.ts: ${flags.length} keys (${count('national')} national flags, ${count('national-coat')} national coats, ${count('subdivision')} subdivision flags, ${count('subdivision-coat')} subdivision coats, ${count('variant')} variants, ${count('extra')} extras, ${count('unmatched')} unmatched)`
  );
  console.log(`src/generated: national.ts (${national.length} flags), ${countryModules.length} country modules, all.ts`);
  console.log(`src/iso-mapping.json: ${split(isoMapping)}`);
  console.log(`src/iso-coa-mapping.json: ${split(coaMapping)}`);
  console.log(`open-flags-api iso-mapping.json: ${split(apiMapping)}`);
  console.log(`open-flags-api iso-coa-mapping.json: ${split(apiCoaMapping)}`);
  console.log(
    `src/named-mapping.json: ${named.size} names (${modernNames.size} English, ${named.size - modernNames.size} legacy; ${shadowed} legacy names left to the English name with the same key, ${legacyOverPolyfill} legacy names kept over a polyfilled English name)`
  );
  console.log(`src/i18n: ${Object.keys(LOCALES).join(', ')}, aliases.json (${Object.keys(aliases).length} codes)`);
  console.log(
    `Wrote ${written} of ${outputs.size} files (${outputs.size - written} unchanged${removed ? `, ${removed} stale country modules removed` : ''}) in ${Date.now() - started}ms${warnings ? `, ${warnings} warnings` : ''}`
  );
}

try {
  main();
} catch (err) {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
}
